### ISSUE TITLE
`$form['node_access_rebuild_progressive_chunk']` should be `$form['chunk']`

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/node_access_rebuild_progressive#4]
Oops, this was my mistake.

`$form['node_access_rebuild_progressive_chunk']` should be `$form['chunk']` so that `system_settings_form()` saves to the right config variable.

**Comment by herbdool** [comment]
@bugfolder I've got an easy PR for this bug. Can you make a release after this?

**Comment by bugfolder** [comment]
@herbdool, give me a few days. Just got back from 3 weeks away, and was hoping to have the bee command working before the release.

**Comment by herbdool** [comment]
@bugfolder no worries.

You could always make another release after this one. The basics are working. I like to make lots of smaller releases so it's easier for folks to download the best version.

**Comment by bugfolder** [comment]
@herbdool, I've made the release as a beta. Still working on the bee command; when I've got that working, I'll do a non-beta release.

**Comment by herbdool** [comment]
Thanks @bugfolder
